### PR TITLE
Remove /b munging from pytest_runtest_setup

### PR DESCRIPTION
**Pull request by jgmize**
Fixes an error when attempting to run mcom-tests against https://bedrock-dev.us-west.moz.works and https://bedrock-dev.eu-west.moz.works due to replacing the `/b` with an empty string

### CODE REVIEW

**Comment by jgmize** [comment]
@rbillings r?

**Comment by davehunt** [comment]
I think there's more cleanup we could do here, such as the command line argument and markers. See https://github.com/mozilla/mcom-tests/commit/f2f15e8f4118d33a5176e65adc4348e879c6150a

**Comment by rbillings** [comment]
I verified that the tests run successfully after this change, I'll wait to hear the response to Dave's question.

**Comment by jgmize** [comment]
We're no longer using the bedrock or skipsprod markers from what I can tell, so I went ahead and removed conftest.py alltogether.

**Comment by davehunt** [comment]
Thanks @jgmize!

**Pull request merged**
