### PR TITLE
Upgrade py.test dependency to 2.7

### PR DESCRIPTION
**Pull request by retornam**
addresses issue #403

### CODE REVIEW

**Comment by retornam** [comment]
this failed because the .travis.yml depends on py.test-xdist. I changed the travis.yml file in #407. It will be best to merge that first and then re-trigger this build

**Comment by rbillings** [comment]
r+ :bowtie:

**Comment by jgmize** [comment]
Unfortunately, this appears to have broken the build. A few examples:

https://webqa-ci.mozilla.com/job/mozilla.org.prod.win7.firefox.saucelabs/208/console
https://webqa-ci.mozilla.com/job/mozilla.org.prod.win8.ie10.saucelabs/221/console
https://webqa-ci.mozilla.com/job/mozilla.org.prod.win7.chrome.saucelabs/209/console

**Comment by davehunt** [comment]
Hmm.. was this tested? pytest 2.7 depends on py>=1.4.26 so that dependency also needs to be updated. See the example mentioned in the original issue: https://github.com/mozilla/Addon-Tests/commit/bfa2336803debe57aaffaed4e1033e5d88f4c198

**Pull request merged**
