### PR TITLE
Fix #408: Remove tests for blog.m.o links.

### LINKED ISSUE #408: Two tests are failing on mozilla.org test suites on dev, stage and prod
The failing tests are `test_major_link_urls_are_valid` in `test_about.py` [1] and `test_that_all_links_are_valid` in `test_notes.py` [2]. It looks like both may be issues with using `requests` to check for validity of links, as the failure messages indicate a `403` when checking the link.

Report of failures can be seen at https://webqa-ci.mozilla.com/view/Mozilla.org/job/mozilla.org.stage/165/HTML_Report/

@jgmize or @pmclanahan would either of you be willing to help investigate and fix this?

[1] https://github.com/mozilla/mcom-tests/blob/master/tests/test_about.py#L122
[2] https://github.com/mozilla/mcom-tests/blob/master/tests/test_notes.py#L23

### PR DESCRIPTION
**Pull request by pmclanahan**

### CODE REVIEW

**Comment by pmclanahan** [comment]
@jgmize r?

**Comment by bobsilverberg** [comment]
Thanks for this @pmclanahan. :)

Just wondering, why do we need to remove these? Is there something we could do differently with `requests`, or do you feel this coverage is unnecessary?

**Comment by pmclanahan** [comment]
I just don't really feel that testing that blog.m.o is working is required. It would be nice to verify that it was a good link, but something about how the new platform for the blogs works is blocking us and I've no time to figure out why. We can't leave them in right now and get a green run, so this seemed the most expedient fix. I did leave commented code and comments so that we'd be reminded later to implement a more appropriate fix if we figure out the deal with the 403s.

**Comment by bobsilverberg** [comment]
Makes sense @pmclanahan. Thanks for the PR.

**Comment by davehunt** [comment]
This shouldn't have been merged as it caused pyflake errors as indicated by the Travis-CI build. Please submit a further patch to address these.

**Comment by davehunt** [comment]
CC @bobsilverberg, @pmclanahan

**Pull request merged**
