### PR TITLE
Fix /aurora and /beta tests for updated redirects.

### PR DESCRIPTION
**Pull request by pmclanahan**

### CODE REVIEW

**Comment by rbillings** [comment]
I'm happy to look at this, but shouldn't it be coming from a feature branch?

**Comment by jgmize** [comment]
this is related to https://github.com/mozilla/bedrock/pull/3360 which has been deployed to demo4 and this is the one failure on http://webqa-ci-staging1.qa.scl3.mozilla.com:8080/job/mozorg.adhoc/39/console (vpn required)

**Comment by jgmize** [comment]
> I'm happy to look at this, but shouldn't it be coming from a feature branch?

This will not pass until https://github.com/mozilla/bedrock/pull/3360 has been merged. I agree with the change from a 302 to a 301, so this test change LGTM, and yes, the PR would ideally be from a feature branch but I don't consider it a blocker for merge.

**Comment by rbillings** [comment]
Agree not a blocker. The 302 to 301 change looks good as does the change to test_redirect.py

**Comment by bobsilverberg** [comment]
LGTM. Everything passes when I run it against https://www-demo4.allizom.org. r+

**Comment by pmclanahan** [comment]
I was just lazy and didn't branch. I'm not planning any other mcom work before this is merged :)

**Pull request merged**
