### PR TITLE
Remove firefox SMS page tests.

### PR DESCRIPTION
**Pull request by gauthierm**
Page is removed as part of Bugzilla 1150713.

### CODE REVIEW

**Comment by davehunt** [comment]
Have we added a redirect test? Not sure if it would be best placed in https://github.com/mozilla/mcom-tests/blob/master/tests/test_redirect.py or https://github.com/mozilla/bedrock/tree/master/test_redirects

**Comment by gauthierm** [comment]
I will add tests to bedrock. Unfortunately the instructions for setting up the `bedrock/test_redirects` tests do not work. I think a required python package is not listed in the dependencies.

**Comment by gauthierm** [comment]
Tests added in https://github.com/gauthierm/bedrock/commit/57c6caf8c87560dd8e72090c2bad86b01a8f8df6

**Comment by gauthierm** [comment]
Fixed bedrock/test_redirect instructions in https://github.com/mozilla/bedrock/pull/3646

**Comment by davehunt** [comment]
r+ thanks!

**Pull request merged**
