### PR TITLE
Skip link_check tests by default

### PR DESCRIPTION
**Pull request by jgmize**
Add --link_check option

### CODE REVIEW

**Comment by jgmize** [comment]
Once this lands we should create a separate jenkins job for at least the dev environment that just runs the tests marked with link_check by adding `--link_check -m link_check` to the py.test arguments

**Comment by stephendonner** [comment]
@davehunt can you take a look at this?  thx!

**Comment by davehunt** [comment]
I would prefer that we ran these tests by default and modify our Jenkins jobs to exclude them based on the mark. This would just mean adding `-m "not link_check"` to the command line for the command line defined in the jobs. We could still add a `--skip-link-checks` command line option, but using `-m` gives us more control over the collection of tests to run.

**Comment by davehunt** [comment]
Let me know if you'd like me to configure the Jenkins jobs according to my last comment. I will also create a single job to exclusively run the link checks.

**Comment by jgmize** [comment]
> I would prefer that we ran these tests by default and modify our Jenkins jobs to exclude them based on the mark. This would just mean adding -m "not link_check" to the command line for the command line defined in the jobs. We could still add a --skip-link-checks command line option, but using -m gives us more control over the collection of tests to run.

I thought it would make things easier by changing the default, but I have no objections if you'd prefer to modify all the existing jenkins jobs to disable the link checks, since it accomplishes the same goal. 

> Let me know if you'd like me to configure the Jenkins jobs according to my last comment. I will also create a single job to exclusively run the link checks.

Yes, please.

**Comment by davehunt** [comment]
Done. I created the following new jobs:
https://webqa-ci.mozilla.com/view/Mozilla.org/job/mozilla.org.dev.links/
https://webqa-ci.mozilla.com/view/Mozilla.org/job/mozilla.org.stage.links/

**Comment by jgmize** [comment]
> Done. I created the following new jobs:
> https://webqa-ci.mozilla.com/view/Mozilla.org/job/mozilla.org.dev.links/
> https://webqa-ci.mozilla.com/view/Mozilla.org/job/mozilla.org.stage.links/

Thanks!

**Pull request closed without merging**
