### PR TITLE
Updated link_check and all other pytest decorators

### PR DESCRIPTION
**Pull request by rbillings**
Addresses Issue #425

### CODE REVIEW

**Comment by jgmize** [comment]
Thanks @rbillings! This lgtm other than the PEP8 violations reported by travis-- just need 2 blank lines instead of one before the class declarations.
r+wc

**Comment by davehunt** [comment]
For what it's worth, I'm r+ adding the linkcheck mark, but r- the rewriting of our mark style, but I won't stand in it's way. As I see it, this adds lines of code for the minimal benefit of reducing some line lengths. I also feel that we lose some readbility by hiding the fact that these decorators are pytest marks up in the top of the file.

On creating new Jenkins jobs for these tests, note that we already have 10 mcom jobs, so we may not want to create an additional job for each environment.

**Comment by jgmize** [comment]
> For what it's worth, I'm r+ adding the linkcheck mark, but r- the rewriting of our mark style, but I won't stand in it's way. As I see it, this adds lines of code for the minimal benefit of reducing some line lengths. I also feel that we lose some readbility by hiding the fact that these decorators are pytest marks up in the top of the file.

I understand your perspective, and appreciate your willingness to compromise :)

> On creating new Jenkins jobs for these tests, note that we already have 10 mcom jobs, so we may not want to create an additional job for each environment.

Agreed-- I was thinking one "link test" job each for dev, stage, and prod; I don't see any point varying by browser or internal grid vs saucelabs.

**Comment by bobsilverberg** [comment]
It looks like this is ready to be merged, based on the discussion above, except that it now has merge conflicts. :(

@rbillings Can you resolve the conflicts and then ping @jgmize to do the merge? As he is a proponent of the code style, I think it appropriate that he do the merge.

**Comment by jgmize** [comment]
I took care of the merge conflicts during a manual merge. Thanks!

**Pull request merged**
