### PR TITLE
Fix tabzilla link tests

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
Notes here: https://people.mozilla.org/~jmize/failing-tabzilla-tests.html

**Comment by jgmize** [comment]
[Fixed link check, but still getting 403s on blog.mozilla.org](https://people.mozilla.org/~jmize/failing-tabzilla-tests.html#sec-3)

**Comment by jgmize** [comment]
@m8ttyB r?

**Comment by m8ttyB** [comment]
A beauty! r+ and merging

**Pull request merged**
