### PR TITLE
Fix flake8 tests by removing comments.

### PR DESCRIPTION
**Pull request by pmclanahan**
Also move flake8 config to a file for easier
and more accurate local runs.

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Thanks @pmclanahan. @davehunt Do you want to r? the Travis config change, as you were the one who initially determined how that was set up?

**Comment by davehunt** [comment]
This prevents users from having custom config files for flake8, which is why I avoided it originally. That said, perhaps that's something we want to have control over? I'd like to hear your opinion @bobsilverberg, but whatever we do here I'd like to apply across all of our repositories, starting with mozwebqa-examples.

**Comment by pmclanahan** [comment]
Pretty sure it doesn't prevent anything. Local users can always do whatever they want on the command line. Bedrock uses flake8 settings in `setup.cfg` so that local users can add `flake8 .` to a git pre-commit hook and know that the PR they're submitting will pass that test since they both use the same settings. I'm happy to remove it, but we've liked the consistency.

**Comment by davehunt** [comment]
@pmclanahan I just meant it prevents users from personalising setup.cfg, and if they do make changes it might cause confusion when those changes appear in their diffs. I might be being overly sensitive though - I do see the advantages. Let's see what @bobsilverberg thinks.

**Comment by bobsilverberg** [comment]
@pmclanahan @davehunt I agree that it would be nice for a repo owner to be able to control the rules that are used by flake8. They should really be the ones dictating the style rules required for the project. I think if anyone wants to have more control there are ways of overriding it, and anyone wanting to do so should be knowledgeable enough to figure out how to do so. r+

**Comment by bobsilverberg** [comment]
@davehunt I added my thoughts yesterday. Do you have any other concerns, or should we merge this?

**Comment by davehunt** [comment]
Merged. @bobsilverberg could you open (or edit existing) issues for our other repositories to follow this new convention of using setup.cfg to configure the flake8 rules? Thanks.

**Pull request merged**
