### PR TITLE
Added 2 tests for the contributor signup page

### PR DESCRIPTION
**Pull request by justinpotts**
These two tests go through the sign up process for a contributor wanting to get involved in coding, and then a contributor wanting to get involved in testing, picking a random subtopic of interest each time.

### CODE REVIEW

**Comment by rbillings** [comment]
This looks really good- nice clean code. Tests pass. +1

**Comment by rbillings** [comment]
Travis is failing on flake8 line length, nothing more. Merging.

**Comment by davehunt** [comment]
Travis was failing because there were too many blank lines:

> ./tests/test_contribute.py:16:1: E303 too many blank lines (3)

Can we file a followup patch to fix this @justinpotts, @rbillings? We already ignore line length in our Travis builds, so they would not cause a build to fail.

**Comment by davehunt** [comment]
Nevermind, it looks like @bobsilverberg fixed it here: https://github.com/mozilla/mcom-tests/pull/414/files#diff-7a01db3a1d4f9eeb3ead33df34a7ef1fL15

**Pull request merged**
